version: "3.9"



x-app: &default-services
  restart: unless-stopped
  environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - ADVERTISE_IP="https://plex.winslow.co.za:443"

services:

  traefik:
      # The latest official supported Traefik docker image
      image: traefik:latest
      # Enables the Traefik Dashboard and tells Traefik to listen to docker
      # enable --log.level=INFO so we can see what Traefik is doing in the log files
      ports:
        # Exposes port 80 for incomming web requests
        - "80:80"
        - "443:443"
        # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
        - "8080:8080"
      restart: unless-stopped
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
        # Copies the Let's Encrypt certificate locally for ease of backing up
        - ./letsencrypt:/letsencrypt
        # Mounts the Traefik static configuration inside the Traefik container
        - ./traefik.yml:/etc/traefik/traefik.yml

  nzbget:
    <<: *default-services
    container_name: nzbget
    image: linuxserver/nzbget:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.rule=Host(`downloads.winslow.co.za`)"
      - "traefik.http.routers.nzbget.service=nzbget"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.http.routers.nzbget.entrypoints=websecure"
      - "traefik.http.routers.nzbget.tls.certresolver=myresolver"
    volumes:
      - /media/downloads:/downloads # download folder
      - ./config/nzbget:/config # config files
      - /media/movies:/movies 
      - /media/tv:/tv 
      - /media/sport:/sport 
      - /media/music:/music 


  sonarr:
    <<: *default-services
    container_name: sonarr
    image: linuxserver/sonarr:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config # config files
      - /media/tv:/tv # tv shows folder
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.sonarr.rule=Host(`series.winslow.co.za`)"
          - "traefik.http.routers.sonarr.service=sonarr"
          - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
          - "traefik.http.routers.sonarr.entrypoints=websecure"
          - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
  radarr:
    <<: *default-services
    container_name: radarr
    image: linuxserver/radarr:latest
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.radarr.rule=Host(`movies.winslow.co.za`)"
          - "traefik.http.routers.radarr.service=radarr"
          - "traefik.http.services.radarr.loadbalancer.server.port=7878"
          - "traefik.http.routers.radarr.entrypoints=websecure"
          - "traefik.http.routers.radarr.tls.certresolver=myresolver"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config # config files
      - /media/movies:/movies # movies folder

  plex:
    <<: *default-services
    container_name: plex-server
    image: linuxserver/plex:latest
    ports: 
        - 32400:32400
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plex.rule=Host(`plex.winslow.co.za`)"
        - "traefik.http.routers.plex.service=plex"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - "traefik.http.routers.plex.entrypoints=websecure"
        - "traefik.http.routers.plex.tls.certresolver=myresolver"
    volumes:
      - ./config/plex/db:/config # plex database
      - ./config/plex/transcode:/transcode # temp transcoded files
      - /media/movies:/movies 
      - /media/tv:/tv 
      - /media/sport:/sport 
      - /media/music:/music 

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  transmission:
    <<: *default-services
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transmission.rule=Host(`transmission.winslow.co.za`)"
        - "traefik.http.routers.transmission.service=transmission"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.tls.certresolver=myresolver"
    volumes:
      - /config/transmission:/config
      - /media:/downloads
      - /media/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

networks:
  default:
    external:  true
    name: proxy
