################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge TLS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: david@winslow.co.za  
      storage: acme.json
      tlsChallenge: true
        # # used during the challenge
        # entryPoint: web
